### ISSUE TITLE
resque-scheduler (2.0.0) getting undefined method `trace_execution_scoped' for Redis::Client:Class

### ISSUE THREAD

**Issue by RaphaelAudet** [evanphx/newrelic-redis#9]
Hi

I just installed the gem newrelic-redis on a project using redis, resque and resque-scheduler. Resque workers are starting fine but the resque-scheduler is getting an undefined method error (the trace log can be found at the end of this issue)

I changed my resque.rake such a in this issue (http://stackoverflow.com/questions/9961044/postgres-error-on-heroku-with-resque/9964924#9964924) but I am still getting the error 

```
2012-10-31 12:17:54 Loading Schedule
2012-10-31 12:17:54 Scheduling move_day_pinned_tasks 
2012-10-31 12:17:54 Scheduling move_week_pinned_tasks 
2012-10-31 12:17:54 Scheduling move_month_pinned_tasks 
2012-10-31 12:17:54 Scheduling send_task_reminders_30_mins_interval 
** Invoke resque:scheduler (first_time)
** Invoke resque:scheduler_setup (first_time)
** Execute resque:scheduler_setup
** Execute resque:scheduler
rake aborted!
undefined method `trace_execution_scoped' for Redis::Client:Class
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/newrelic-redis-1.3.2/lib/newrelic_redis/instrumentation.rb:33:in `call_with_newrelic_trace'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:681:in `block in del'
/usr/local/rvm/rubies/ruby-1.9.3-p125-perf/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/redis-2.2.2/lib/redis.rb:680:in `del'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.0.3/lib/redis/namespace.rb:213:in `method_missing'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/resque-scheduler-2.0.0.g/lib/resque/scheduler.rb:103:in `load_schedule!'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/resque-scheduler-2.0.0.g/lib/resque/scheduler.rb:45:in `run'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/resque-scheduler-2.0.0.g/lib/resque_scheduler/tasks.rb:23:in `block (2 levels) in <top (required)>'
/var/www/my_project_staging/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
```

**Comment by evanphx** [comment]
I'm sure this is fixed in the current version.
